[[contracts]]
bytecode_path = "./contracts/0xb89a6778d1efe7a5b7096757a21b810cc2886fa1.hex"
first_evm_version = "REGOLITH"

[[contracts]]
bytecode_path = "./contracts/0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865.hex"
first_evm_version = "REGOLITH"

[[contracts]]
bytecode_path = "./contracts/0x41ff9aa7e16b8b1a8a8dc4f0efacd93d02d071c9.hex"
first_evm_version = "REGOLITH"

[[contracts]]
bytecode_path = "./contracts/0xc4f981189558682f15f60513158b699354b30204.hex"
first_evm_version = "REGOLITH"

[[contracts]]
bytecode_path = "./contracts/0x9e5aac1ba1a2e6aed6b32689dfcf62a509ca96f3.hex"
first_evm_version = "REGOLITH"

[[contracts]]
bytecode_path = "./contracts/0x4200000000000000000000000000000000000006.hex"
first_evm_version = "REGOLITH"

[[contracts]]
bytecode_path = "./contracts/0x81d70ef88511d5c6552249f9bde184a8cf4ff1ce.hex"
first_evm_version = "REGOLITH"

[[contracts]]
bytecode_path = "./contracts/0x862d72ec947b0054c6c98cced4c140a05b9ec8db.hex"
first_evm_version = "REGOLITH"

[[contracts]]
bytecode_path = "./contracts/0x678aa4bf4e210cf2166753e054d5b7c31cc7fa86.hex"
first_evm_version = "REGOLITH"

[[contracts]]
bytecode_path = "./contracts/0xb01d49c26416a352fac4fbb3d555d5f2543e3247.hex"
first_evm_version = "REGOLITH"
