[[contracts]]
bytecode_path = "./contracts/0xcf97ADEBaD696781e6b75280Ba11040A1A20C27a.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0x03B6f01EB419915B1F157e67C8263101ddd6E15e.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0x5460ae5e02A33957b57E306F1f372306362cB8d2.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0xAcb68Eab051BCE90B3d76B21fd871dadd6da332b.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0x0fc1B3E19458D2fC8A8F56f06E2dDc105257e00F.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0x3c76649cbae809e18bb577a9e291935f81a00195.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0xFe7079971c388463D18E83fbfF363936150E9B92.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0x2311EF80DF4AF230c49805f96CEA006bA310f87E.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0x7DAf52228Aa6c6B6Ab17E12dAFAe961987C6CFa6.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0x8cd6bcBD8cc2c23Cbc3f7F1b6Ace961cbA86fe16.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0x44CD9453C904Be9AABD3Ec947e112206D3f0161D.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0xA0F18D70a1CbFE8445941EeE7a026b7532378eA8.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0x2c085411ca401a84a9D98DEc415282FA239D53bB.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0xb5fed169dbf87ca46a12fe47ba0d12b4d3ac80ea.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0xf94810F8d178063d313E429d4b40F85B92BD61f8.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0x3375bDec9745530648538D56c4d16A0E2Cb9156c.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0x00a9De8Af37a3179d7213426E78Be7DFb89F2b19.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0xfE6AF84f2fA6f2C24c7afB05337f7c2527dD2709.hex"
first_evm_version = "BEDROCK"

[[contracts]]
bytecode_path = "./contracts/0xF2b05C3fAF117C5D8301e74253F1Cb84271aAAD7.hex"
first_evm_version = "BEDROCK"

