      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@nextest
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y liburing-dev pkg-config libclang-dev
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run e2e tests
        run: |
          cargo nextest run \
            --locked --features "asm-keccak" \
            --workspace \
            --exclude 'example-*' \
            --exclude 'exex-subscription' \
            --exclude 'ef-tests' \
            --exclude 'op-reth' \
            --exclude 'reth' \
            -E 'binary(e2e_testsuite)'
