      - uses: actions/checkout@v6
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build ${{ matrix.chain.bin }}
        run: make ${{ matrix.chain.build }}
      - name: Run sync with ERA enabled
        run: |
          ${{ matrix.chain.bin }} node \
            --chain ${{ matrix.chain.chain }} \
            --debug.tip ${{ matrix.chain.tip }} \
            --debug.max-block ${{ matrix.chain.block }} \
            --debug.terminate \
            --era.enable
      - name: Verify the target block hash
        run: |
          ${{ matrix.chain.bin }} db --chain ${{ matrix.chain.chain }} get static-file headers ${{ matrix.chain.block }} \
            | grep ${{ matrix.chain.tip }}
      - name: Run stage unwind for 100 blocks
        run: |
          ${{ matrix.chain.bin }} stage unwind num-blocks 100 --chain ${{ matrix.chain.chain }}
      - name: Run stage unwind to block hash
        run: |
          ${{ matrix.chain.bin }} stage unwind to-block ${{ matrix.chain.unwind-target }} --chain ${{ matrix.chain.chain }}
